version: '3.1'

services:
  vue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: soha 

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

volumes:
  mongo-data:
    driver: local
